basePath: /
info:
  contact: {}
  description: My first API
  license:
    name: MIT
  title: CRUD app
  version: "1.0"
paths:
  /calculator/add/{num1}/{num2}:
    get:
      consumes:
      - text/plain
      parameters:
      - description: First number
        in: path
        name: num1
        required: true
        type: integer
      - description: Second number
        in: path
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Addition of two numbers
      tags:
      - Calculator
  /calculator/count:
    get:
      consumes:
      - text/plain
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Count of operations
      tags:
      - Calculator
  /calculator/sub/{num1}/{num2}:
    get:
      consumes:
      - text/plain
      parameters:
      - description: First number
        in: path
        name: num1
        required: true
        type: integer
      - description: Second number
        in: path
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Subtraction of two numbers
      tags:
      - Calculator
schemes:
- http
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
